---
name: Build, test and push images

variables:
  imageName: chialab/php
  imageNameDev: chialab/php-dev
  DOCKER_BUILDKIT: 1

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: ListTags
    steps:
    - bash: echo "##vso[task.setVariable variable=tags;isOutput=true]{'5.4':{'buildPath':'5.4', 'tag':'5.4'}, '5.4-apache':{'buildPath':'5.4/apache', 'tag':'5.4-apache'}}"
      name: matrix

  - job: BuildAndPush
    dependsOn: ListTags
    strategy:
      matrix: $[ dependencies.ListTags.outputs['matrix.tags'] ]
    steps:
      - task: Docker@2
        displayName: Build base image
        inputs:
          command: build
          DockerFile: $(buildPath)/Dockerfile
          buildContext: $(buildPath)
          repository: $(imageName)
          tags: $(tag)
        
      - task: CMake@1
        displayName: Test base image
        inputs:
          cwd: '.'
          cmakeArgs: test VERSION=$(tag)

      - task: Docker@2
        displayName: Build dev image
        inputs:
          command: build
          DockerFile: dev/$(buildPath)/Dockerfile
          buildContext: dev/$(buildPath)
          repository: $(imageNameDev)
          tags: $(tag)

      - task: CMake@1
        displayName: Test dev image
        inputs:
          cwd: dev
          cmakeArgs: test VERSION=$(tag)
